---
title: "MTurkR code for approving/awarding bonuses"
author: "Molly Offer-Westort"
date: "`r format(Sys.Date())`"
output: github_document
---

## Setup

If starting a new session, load packages and set AWS access key.
```{r files, echo=FALSE}
# AWS credentials file
f <- file.path("~", "Box Sync", "Admin", "Mturk_Credentials", "credentials.csv")
credentials_file <- read.csv(file = f)
# set verbose to FALSE
options(MTurkR.verbose = FALSE)
# Behavior raw data
f <- file.path("~", "Box Sync", "Research", "Behavior", 
               "Shared_Behavior research MOW", "group-shocks", "fall2017", 
               "MTurk", "Raw_Data")
```

```{r aws}
Sys.setenv(AWS_ACCESS_KEY_ID = credentials_file$Access.Key.Id)
Sys.setenv(AWS_SECRET_ACCESS_KEY = credentials_file$Secret.Access.Key)
```

```{r library}
library(MTurkR)
library(foreign)
```


## Approve assignments, award bonuses
```{r approval, eval = FALSE}
workers <- GetAssignments(hit = GetReviewableHITs()[,1]) # get all reviewable hits
workers <- workers[which(is.na(workers$ApprovalTime)),] # ignore already approved ones
ApproveAssignment(workers$AssignmentId) # Approve assignments
```

Match to survey (here, the filepath has already been saved as `f`). 
```{r match, eval = FALSE}
dat <- read.csv(file=f, as.is=TRUE)
workers$surveycode <- trimws(workers$surveycode, which = "both")
```

Assign bonuses. 
```{r bonus, eval = FALSE}
dat$bonus <- dat$stage1/100+ .1
dat$contrib_text <- paste0("Thank you for participating in this survey. Your bonus is calculated as follows: Your stage 1 earnings were ",
                           dat$stage1,
                           " tokens. Each token is worth $0.01. Your stage 1 bonus is $",
                           dat$stage1/100, 
                           ". In stage 2, you were randomly assigned the decider role. All deciders are assigned a fixed stage two earnings of 10 tokens. Each token is worth $0.01. Your total bonus is $",
                           dat$bonus, ".")


payout <- merge(workers, dat[, c("bonus", "contrib_text", "confirmation_code")], 
                by.x = "surveycode", 
                by.y = "confirmation_code", all.x=TRUE)

# Bonus workers with valid survey codes
payout <- payout[which(payout$surveycode!=""), ]


# Pay bonus
GrantBonus(workers=payout$WorkerId, assignments=payout$AssignmentId,
           amounts=payout$bonus, reasons=payout$contrib_text)
```
